### ISSUE TITLE
"object color not found"

### ISSUE THREAD

**Issue by ari328** [roman-tremmel/FASTGWASMAN#2]
Hi there, I've been trying to use the fast_manhattan function but keep getting this error message. I've tried running just the first line (without addition of horizontal lines), but keep getting it. Any clue what's wrong? Thanks!

<img width="749" alt="Screen Shot 2021-12-11 at 9 54 00 AM" src="https://user-images.githubusercontent.com/95948060/145660008-4c82ef2f-36f6-4473-87bf-e74339146c70.png">

**Comment by roman-tremmel** [comment]
Dear ari, 

using the most recent version `ggfastman_1.2`, I don't get any error when running `fast_manhattan(gwas_data, build = "hg18", speed = "fast", color1 = "black", color2 = "grey")`. Which version do you used?

In addition, I recommend to use a more tidyverse approach to label selected variants. 

    fast_manhattan(gwas_data, build = "hg18", speed = "fast", color1 = "black", color2 = "grey") +
    ggrepel::geom_text_repel(data= . %>% filter(pvalue<10^-80), aes(label = rsid))

Best, 
Roman
