### ISSUE TITLE
Custom genome

### ISSUE THREAD

**Issue by mariosaare** [roman-tremmel/FASTGWASMAN#3]
Hi,

Thanks for this great package! I was wondering, if it would be possible to implement an option to use a custom set of chromosomes for the Manhattan plot? In my specific case, the data has chromosomes labelled from 1 to 23, where 23 is the X chromosome. Maybe the build argument could accept a named vector of chromosome length in addition to the built-in options hg18, hg19 and hg38?

Best regards,
Mario

**Comment by knutgroener** [comment]
Good point. But as the function should have warned you with `"Numeric 'chr' column detected. Tried to transform to character by prefixing 'chr'.` it is not the recommended way to input a numeric chromosome identifier. But you are right, I think I should revise the code here a little bit. 

A quik solution could be to transform your `chr` column to character beforehand and change "chr23" to "chrX". 

```
library(tidyverse)
gwas_data %>% 
  bind_rows(filter(gwas_data, chr=="chr22") %>% mutate(chr="chrX")) %>% 
  bind_rows(filter(gwas_data, chr=="chr21") %>% mutate(chr="chrY")) %>% 
  fast_manhattan(build='hg18', speed = "fast", dodge_x = T)
```

**Comment by roman-tremmel** [comment]
Good point. But as the function should have warned you with `"Numeric 'chr' column detected. Tried to transform to character by prefixing 'chr'.` it is not the recommended way to input a numeric chromosome identifier. But you are right, I think I should revise the code here a little bit.

A quik solution could be to transform your `chr` column to character beforehand and change "chr23" to "chrX".

```
library(tidyverse)
gwas_data %>% 
  bind_rows(filter(gwas_data, chr=="chr22") %>% mutate(chr="chrX")) %>% 
  bind_rows(filter(gwas_data, chr=="chr21") %>% mutate(chr="chrY")) %>% 
  fast_manhattan(build='hg18', speed = "fast", dodge_x = T)
```

**Comment by mariosaare** [comment]
Thank you for the suggestion! You are right - replacing the chromosome labels is the simplest solution. 

Best regards,
Mario
